apiVersion: apps/v1
kind: Deployment
metadata:
  name: rus-itmo
  labels:
    app: rus-itmo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rus-itmo
  template:
    metadata:
      labels:
        app: rus-itmo
    spec:
      containers:
      - name: ifilyaninitmo
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          value: Ruslan_react_app
        - name: REACT_APP_COMPANY_NAME
          value: Itmo_react_app
        ports:
        - containerPort: 3000