apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
   name: ippool-one
spec:
   cidr: 10.0.0.0/24
   ipipMode: Always
   natOutgoing: true
   nodeSelector: zone == "one"
---

apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
   name: ippool-two
spec:
   cidr: 10.0.1.0/24
   ipipMode: Always
   natOutgoing: true
   nodeSelector: zone == "two"